### PR TITLE
Fix SDK path issues with ubuntu-24.04

### LINKED ISSUE #400: Error on Ubuntu-24.04
Hello,

First of all, emulators on Linux images are pretty cool. Having said that, I've noticed an issue - it doesn't work on Ubuntu-24.04 (beta). We need to use Ubuntu-22.04 (latest).

Just wanted to file this as an issue, because it took me some time to figure out why my CI is red.

Here's a sample run with Ubuntu-22.04 and Ubuntu-24.04 - https://github.com/ViliusSutkus89/android-emulator-runner-ubuntu-24.04/actions/runs/9594927854

Ubuntu-24.04 errors out:
```
2024-06-20T09:23:17.9214746Z [command]/usr/bin/sh -c \echo no | avdmanager create avd --force -n test --abi 'default/x86' --package 'system-images;android-29;default;x86'
2024-06-20T09:23:18.6029378Z Loading local repository...                                                     
2024-06-20T09:23:18.6035642Z [=========                              ] 25% Loading local repository...       
2024-06-20T09:23:18.6036583Z [=========                              ] 25% Fetch remote repository...        
2024-06-20T09:23:18.6045879Z [=======================================] 100% Fetch remote repository...       
2024-06-20T09:23:18.7430306Z Do you wish to create a custom hardware profile? [no] [command]/usr/bin/sh -c \printf 'hw.cpu.ncore=2
2024-06-20T09:23:18.7431804Z ' >> /home/runner/.android/avd/test.avd/config.ini
2024-06-20T09:23:18.7449816Z /usr/bin/sh: 1: cannot create /home/runner/.android/avd/test.avd/config.ini: Directory nonexistent
2024-06-20T09:23:18.7456105Z ##[endgroup]
2024-06-20T09:23:18.7457248Z ##[group]Terminate Emulator
```

[Workflow file](https://github.com/ViliusSutkus89/android-emulator-runner-ubuntu-24.04/actions/runs/9594927854/workflow):
```yaml
name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: /bin/true
```

### PR DESCRIPTION
**Pull request by ychescale9**
Resolves #400

### CODE REVIEW

File: lib/sdk-installer.js [hunk 1]
```diff
@@ -53,6 +53,9 @@ function installAndroidSdk(apiLevel, target, arch, channelId, emulatorBuild, ndk
             const isOnMac = process.platform === 'darwin';
             const isArm = process.arch === 'arm64';
             const cmdlineToolsPath = `${process.env.ANDROID_HOME}/cmdline-tools`;
+            if (fs.existsSync(cmdlineToolsPath)) {
+                yield io.rmRF(cmdlineToolsPath);
+            }
```
Comment (mikehardy) [inline lib/sdk-installer.js]: This may be a simpler / better approach than #411 - but with 411 there is the possibility we skip the install if the runner image ever has the updated version. That may have value

However I see this nice `io.rmRF` call and that's better than I do in 411 - I was shelling out to rm things

File: src/sdk-installer.ts [hunk 2]
```diff
@@ -19,11 +19,11 @@ export async function installAndroidSdk(apiLevel: string, target: string, arch:
...
-    if (!isOnMac) {
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/platform-tools -R`);
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/cmdline-tools/latest -R`);
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/build-tools/${BUILD_TOOLS_VERSION} -R`);
-    }
+    // if (!isOnMac) {
+    //   await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/platform-tools -R`);
+    //   await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/cmdline-tools/latest -R`);
+    //   await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/build-tools/${BUILD_TOOLS_VERSION} -R`);
+    // }
```
Comment (mikehardy) [inline src/sdk-installer.ts]: not sure why the chown was there in the first place, but at least to have it not fail - #412 works well

File: src/sdk-installer.ts [hunk 3]
```diff
@@ -19,12 +19,6 @@ export async function installAndroidSdk(apiLevel: string, target: string, arch:
     const isOnMac = process.platform === 'darwin';
     const isArm = process.arch === 'arm64';
 
-    if (!isOnMac) {
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/platform-tools -R`);
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/cmdline-tools/latest -R`);
-      await exec.exec(`sh -c \\"sudo chown $USER:$USER ${process.env.ANDROID_HOME}/build-tools/${BUILD_TOOLS_VERSION} -R`);
-    }
```
Comment (ychescale9) [inline src/sdk-installer.ts:26]: Originally we needed to change the owner to accept preview SDK license: https://github.com/ReactiveCircus/android-emulator-runner/commit/49a3d042e9cc6a9f969d767b7e63b59d85a5cb83#diff-b14a072bf3d3c4d7027a549c57f0c1880f60206c24fc202ce4471ab9c0a5881cR23-R28

But this seems no longer required.
